.travis.yml, Classes/Asset/TagRenderer.php, Classes/Asset/TagRendererInterface.php, Classes/Middleware/PreloadAssetsMiddleware.php, Configuration/RequestMiddlewares.php, Tests/Unit/Asset/TagRendererTest.php, composer.json, ext_emconf.php, ext_localconf.php
- This is the preparation of a new Major Release for Version 9.5 and 10.0 only
=> [FEATURE] Add preload HTTP/2 with Middleware

Classes/Asset/TagRenderer.php, Classes/Middleware/PreloadAssetsMiddleware.php
=> [TASK] Take TYPO3 versioning configuration into account

Classes/Asset/JsonManifestVersionStrategy.php, Classes/Asset/TagRenderer.php, Classes/Integration/AssetRegistry.php, Classes/Integration/AssetRegistryInterface.php, Classes/Integration/Filesystem.php, Classes/Integration/FilesystemInterface.php, Classes/Middleware/PreloadAssetsMiddleware.php, Classes/ViewHelpers/AssetViewHelper.php, Classes/ViewHelpers/PreloadViewHelper.php, Configuration/TypoScript/constants.typoscript, Configuration/TypoScript/setup.typoscript, README.md, Tests/Unit/Asset/JsonManifestVersionStrategyTest.php, Tests/Unit/Asset/TagRendererTest.php, Tests/Unit/Integration/AssetRegistryTest.php, Tests/Unit/ViewHelpers/AssetViewHelperTest.php, Tests/Unit/ViewHelpers/PreloadViewHelperTest.php, ext_localconf.php
=> Task/issue 8 generate preload links Viewhelper

Classes/Asset/TagRenderer.php, Classes/Asset/TagRendererInterface.php, Classes/Middleware/PreloadAssetsMiddleware.php, Classes/ViewHelpers/RenderWebpackLinkTagsViewHelper.php, Classes/ViewHelpers/RenderWebpackScriptTagsViewHelper.php, Tests/Unit/Asset/TagRendererTest.php, Tests/Unit/ViewHelpers/RenderWebpackLinkTagsViewHelperTest.php, Tests/Unit/ViewHelpers/RenderWebpackScriptTagsViewHelperTest.php
=> [TASK] Add option to exclude entrypoints from asset registration

Classes/Integration/AssetRegistry.php, Classes/Integration/EntryLookupFactory.php, Classes/Integration/PackageFactory.php, Classes/Integration/SettingsService.php, Classes/Integration/SettingsServiceInterface.php, Classes/Middleware/PreloadAssetsMiddleware.php, Tests/Unit/Integration/AssetRegistryTest.php, Tests/Unit/Integration/EntryLookupFactoryTest.php, Tests/Unit/Integration/PackageFactoryTest.php, Tests/Unit/Integration/SettingsServiceTest.php, Tests/Unit/Middleware/PreloadAssetsMiddlewareTest.php
- Convert values from settings retrieved by SettingsService explicitly
=> [TASK] Add dedicated access methods for class SettingsService

Classes/Middleware/PreloadAssetsMiddleware.php, Classes/ViewHelpers/AssetViewHelper.php, Tests/Unit/ViewHelpers/AssetViewHelperTest.php, ext_localconf.php
- In order to use EXT: we resolve the pathToFile argument correctly
Resolves: #8
=> [BUGFIX] Resolve pathToFile

Classes/Integration/PageRendererHooks.php, Tests/Functional/Fixtures/Frontend/Resources/Public/entrypoints.json, Tests/Functional/IncludeFilesTest.php, Tests/Unit/Asset/TagRendererTest.php
=> Fix inclusion of integrity hashes

.gitattributes
=> [TASK] Add more files to .gitattributes

README.md
=> [TASK] Use speaking namespace for ViewHelpers

Classes/Asset/EntrypointLookup.php, Classes/Integration/CacheFactory.php, Classes/Integration/EntryLookupFactory.php, Configuration/TypoScript/constants.typoscript, Configuration/TypoScript/setup.typoscript, Tests/Unit/Asset/EntrypointLookupTest.php, Tests/Unit/Integration/EntryLookupFactoryTest.php, composer.json
=> [TASK] Add strictMode config

Classes/Asset/TagRenderer.php, Tests/Functional/Fixtures/Frontend/MainRendererAbsRefPrefix.typoscript, Tests/Functional/Fixtures/Frontend/Resources/Public/entrypoints.json, Tests/Functional/IncludeFilesTest.php
=> [TASK] Enable config.absRefPrefix behind the scenes

.github/workflows/ci.yaml, .github/workflows/code_coverage.yaml
=> [TASK] Run code coverage only on master

Classes/Asset/TagRenderer.php
=> [TASK] Remove leading slash if file is inlined

.github/workflows/ci.yaml, .gitignore, Classes/Asset/TagRenderer.php, Configuration/TypoScript/constants.typoscript, Tests/Functional/Fixtures/Frontend/MainRendererHtml5.typoscript, Tests/Functional/IncludeFilesTest.php, composer.json
=> [TASK] Do not add type if html5 doctype

Classes/Asset/TagRenderer.php
Check valid domain also with absRefPrefix set to e.g. https://www.test.de
=> Update TagRenderer.php removeLeadingSlash method and use additionalAbsRefPrefixDirectories in order to generate abs links to ressources

.github/workflows/ci.yaml, Classes/Asset/EntrypointLookup.php, README.md, composer.json, ext_localconf.php
=> [TASK] Remove default file cache

Classes/Asset/TagRenderer.php
=> [BUGFIX] Check array key [config][doctype]

.github/workflows/ci.yaml, Classes/Asset/EntrypointLookupInterface.php, Classes/Asset/TagRenderer.php, Classes/Asset/TagRendererInterface.php, Classes/Integration/Filesystem.php, Classes/Middleware/AssetsMiddleware.php, Classes/ViewHelpers/SvgViewHelper.php, Tests/Functional/IncludeFilesTest.php, Tests/Unit/Asset/EntrypointLookupTest.php, Tests/Unit/Asset/TagRendererTest.php, Tests/Unit/Integration/EntryLookupFactoryTest.php, Tests/Unit/ViewHelpers/DnsPrefetchViewHelperTest.php, Tests/Unit/ViewHelpers/PreconnectViewHelperTest.php, Tests/Unit/ViewHelpers/PrefetchViewHelperTest.php, Tests/Unit/ViewHelpers/PreloadViewHelperTest.php, Tests/Unit/ViewHelpers/PrerenderViewHelperTest.php, Tests/Unit/ViewHelpers/RenderWebpackLinkTagsViewHelperTest.php, Tests/Unit/ViewHelpers/RenderWebpackScriptTagsViewHelperTest.php, Tests/Unit/ViewHelpers/SvgViewHelperTest.php, composer.json, phpstan-baseline.neon, phpstan.neon, rector.php
=> [TASK] Harden phpstan rules

.gitignore, Classes/Integration/Filesystem.php, Classes/Integration/PageRendererHooks.php, Classes/Middleware/AssetsMiddleware.php, Classes/ViewHelpers/Stimulus/AbstractViewHelper.php, Classes/ViewHelpers/Stimulus/ActionViewHelper.php, Classes/ViewHelpers/Stimulus/ControllerViewHelper.php, Classes/ViewHelpers/Stimulus/TargetViewHelper.php, Tests/Unit/ViewHelpers/AssetViewHelperTest.php, Tests/Unit/ViewHelpers/DnsPrefetchViewHelperTest.php, Tests/Unit/ViewHelpers/PreconnectViewHelperTest.php, Tests/Unit/ViewHelpers/PrefetchViewHelperTest.php, Tests/Unit/ViewHelpers/PreloadViewHelperTest.php, Tests/Unit/ViewHelpers/PrerenderViewHelperTest.php, Tests/Unit/ViewHelpers/RenderWebpackLinkTagsViewHelperTest.php, Tests/Unit/ViewHelpers/RenderWebpackScriptTagsViewHelperTest.php, Tests/Unit/ViewHelpers/Stimulus/ActionViewHelperTest.php, Tests/Unit/ViewHelpers/Stimulus/ControllerViewHelperTest.php, Tests/Unit/ViewHelpers/Stimulus/TargetViewHelperTest.php, Tests/Unit/ViewHelpers/SvgViewHelperTest.php, Tests/Unit/ViewHelpers/ViewHelperBaseTestcase.php, Tests/Unit/ViewHelpers/WebpackCssFilesViewHelperTest.php, Tests/Unit/ViewHelpers/WebpackJsFilesViewHelperTest.php, composer.json, ext_localconf.php, phpstan.neon, rector.php
=> Add ViewHelper to ease usage of stimulusjs

Classes/Form/FormDataProvider/RichtextEncoreConfiguration.php, Tests/Unit/Form/FormDataProvider/RichtextEncoreConfigurationTest.php
Using contentsCss with an array was broken.
Added testcases for different types of contentsCss.
Fixes #127
=> Fixed RTE multiple CSS files.

Classes/Asset/EntrypointLookup.php
Fixes "PHP Warning: Undefined array key"
=> [TASK] Avoid PHP8 warning

Classes/Asset/TagRenderer.php, ecs.php
=> TASK: Do not remove leading slash for absRefPrefix

Classes/Integration/Filesystem.php, Classes/ValueObject/FileType.php, Classes/ViewHelpers/SvgViewHelper.php
=> Add fallback if image cannot be found

Classes/Integration/Filesystem.php, Classes/Integration/FilesystemInterface.php, Classes/Integration/PackageFactory.php, Classes/Integration/PackageFactoryInterface.php, Classes/Middleware/AssetsMiddleware.php, Classes/ValueObject/JsonPackage.php, Classes/ViewHelpers/AssetViewHelper.php
=> TASK: Resolve relative file path for assets

Classes/ViewHelpers/AssetViewHelper.php
=> TASK: Fix regression of AssetViewHelper

README.md
=> TASK: Enhance README.md

ext_localconf.php
=> TASK: Support flexforms for encore css
